services:
  - type: web
    name: mpscsc-claims-portal
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES
        value: 7d
      - key: ADMIN_EMAIL
        value: admin@mpscsc.gov.in
      - key: ADMIN_PASSWORD
        value: Admin@123
      - key: ADMIN_NAME
        value: MPSCSC Administrator
      - key: ADMIN_MOBILE
        value: 9876543210
